"use client";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./reduxStore";
import { Container, CssBaseline } from "@mui/material";



// export const metadata: Metadata = {
//   title: "Create Next Todo App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <Provider store={store}>
        <CssBaseline/>
        <Container>
        {children}
        </Container>
        </Provider>
      </body>
    </html>
  );
}
